title: Beneah Kombe
description: Chronicles of Beneah Kombe
url: "https://kombeneah.com"
baseurl: ""

# Author information
author:
  name: Beneah Kombe
  email: kombeneah@gmail.com

# Social links
social:
  email: info@kombeneah.com
  linkedin: https://www.linkedin.com/in/kombeneah
  github: https://github.com/kombeneah
  twitter: https://twitter.com/kombeneah
  twitter_username: kombeneah

# SEO settings
seo:
  locale: en_US
  default_image: /assets/images/default-og-image.jpg

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/

# Cloudflare Pages build settings
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
